coverage:
  status:
    project:
      default:
        target: 28%
        threshold: 1%
    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "reach,diff,flags,files"
  require_changes: false