from __future__ import annotations

import json

from lakelogic.ai import contract_enricher as ce


class DummyResponse:
    def __init__(self, text, parsed=None, usage=None, fail_parse=False):
        self.text = text
        self._parsed = parsed
        self.usage = usage or {}
        self._fail_parse = fail_parse

    def as_json(self):
        if self._fail_parse:
            raise json.JSONDecodeError("bad", self.text, 0)
        return self._parsed


class DummyClient:
    def __init__(self, response):
        self.response = response
        self.calls = []

    def chat(self, **kwargs):
        self.calls.append(kwargs)
        return self.response


def test_build_user_prompt_truncates_samples_and_includes_dataset_name():
    prompt = ce._build_user_prompt(
        [{"name": "email", "type": "string", "required": True}],
        [{"email": "x" * 120}],
        "customers",
    )

    assert "Dataset: customers" in prompt
    assert "- email (string, required)" in prompt
    assert "## Sample Data (1 rows)" in prompt
    assert "..." in prompt


def test_enrich_contract_skips_when_no_fields(monkeypatch):
    warnings = []
    monkeypatch.setattr(ce.logger, "warning", warnings.append)
    contract = {"model": {"fields": []}}
    assert ce.enrich_contract(contract) is contract
    assert any("No fields in contract" in message for message in warnings)


def test_enrich_contract_merges_ai_enrichment_from_polars_samples(monkeypatch):
    fields = [{"name": "email", "type": "string"}, {"name": "status", "type": "string"}]
    contract = {
        "dataset": "customers",
        "model": {"fields": fields},
        "quality": {"row_rules": [{"sql": "status IS NOT NULL"}]},
        "info": {"description": "Generated by lakelogic bootstrap."},
    }

    class SampleDf:
        def head(self, size):
            return self

        def to_dicts(self):
            return [{"email": "user@example.com", "status": "active"}]

    response = DummyResponse(
        text="ignored",
        parsed={
            "fields": [
                {"name": "email", "description": "Customer email", "pii": True, "pii_type": "email", "pii_remediation": "hash"},
                {"name": "status", "description": "Lifecycle status", "pii": False},
            ],
            "suggested_rules": [
                {"sql": "status IS NOT NULL", "description": "duplicate"},
                {"sql": "email LIKE '%@%.%'", "description": "email shape"},
            ],
            "summary": "Customer master dataset",
            "domain": "crm",
            "data_layer": "silver",
        },
        usage={"prompt_tokens": 10, "completion_tokens": 5},
    )
    monkeypatch.setattr("lakelogic.ai.provider.get_llm_client", lambda **kwargs: DummyClient(response))

    enriched = ce.enrich_contract(contract, SampleDf(), provider="openai")
    assert enriched["model"]["fields"][0]["description"] == "Customer email"
    assert enriched["model"]["fields"][0]["pii"] is True
    assert enriched["model"]["fields"][0]["classification"] == "email"
    assert enriched["model"]["fields"][0]["pii_remediation"] == "hash"
    assert enriched["quality"]["row_rules"] == [
        {"sql": "status IS NOT NULL"},
        {"sql": "email LIKE '%@%.%'", "description": "email shape"},
    ]
    assert enriched["info"]["description"] == "Customer master dataset"
    assert enriched["metadata"] == {"domain": "crm", "data_layer": "silver"}


def test_enrich_contract_supports_pandas_samples_and_json_repair(monkeypatch):
    contract = {
        "dataset": "orders",
        "model": {"fields": [{"name": "id", "type": "integer"}]},
        "info": {"title": "Orders"},
    }

    class SampleDf:
        def head(self, size):
            return self

        def to_dict(self, orient="records"):
            return [{"id": 1}]

    response = DummyResponse(text="broken", fail_parse=True)
    monkeypatch.setattr("lakelogic.ai.provider.get_llm_client", lambda **kwargs: DummyClient(response))
    monkeypatch.setattr("lakelogic.ai.data_generator._repair_llm_json", lambda text: {"fields": [], "summary": "Orders summary"})
    warnings = []
    monkeypatch.setattr(ce.logger, "warning", warnings.append)

    enriched = ce.enrich_contract(contract, SampleDf(), provider="openai")
    assert enriched["info"]["description"] == "Orders summary"
    assert any("required JSON repair" in message for message in warnings)


def test_enrich_contract_returns_original_on_unrepairable_json_and_preserves_existing_metadata(monkeypatch):
    contract = {
        "dataset": "orders",
        "model": {"fields": [{"name": "id", "type": "integer"}]},
        "info": {"description": "Keep this"},
        "metadata": {"domain": "existing", "data_layer": "bronze"},
    }
    response = DummyResponse(text="broken", fail_parse=True)
    monkeypatch.setattr("lakelogic.ai.provider.get_llm_client", lambda **kwargs: DummyClient(response))
    monkeypatch.setattr("lakelogic.ai.data_generator._repair_llm_json", lambda text: None)
    errors = []
    debugs = []
    monkeypatch.setattr(ce.logger, "error", errors.append)
    monkeypatch.setattr(ce.logger, "debug", debugs.append)

    enriched = ce.enrich_contract(contract, None, provider="openai")
    assert enriched is contract
    assert enriched["info"]["description"] == "Keep this"
    assert enriched["metadata"] == {"domain": "existing", "data_layer": "bronze"}
    assert any("Failed to parse AI response as JSON" in message for message in errors)
    assert any("Raw response" in message for message in debugs)