"""Writes the complex samples into data/: nested JSON, nested XML, a multi-tab Excel."""
import json
from pathlib import Path

D = Path(__file__).parent / "data"
D.mkdir(exist_ok=True)

orders = [
    {"order_id": 5001, "placed_at": "2026-10-01",
     "customer": {"id": "C1", "name": "Ada", "address": {"city": "London", "country": "GB"}},
     "items": [{"sku": "A1", "qty": 2, "price": 9.5}, {"sku": "B2", "qty": 1, "price": 20.0}]},
    {"order_id": 5002, "placed_at": "2026-10-02",
     "customer": {"id": "C2", "name": "Bo", "address": {"city": "Paris", "country": "FR"}},
     "items": [{"sku": "C3", "qty": 5, "price": 1.0}]},
    {"order_id": 5003, "placed_at": "not-a-date",           # bad date -> quarantined
     "customer": {"id": "C3", "name": "Cy", "address": {"city": "Rome", "country": "IT"}},
     "items": [{"sku": "A1", "qty": -1, "price": 9.5}]},     # bad qty -> quarantined
]
(D / "orders_nested.json").write_text(json.dumps(orders, indent=2))

(D / "orders_nested.xml").write_text("""<?xml version="1.0"?>
<export xmlns="urn:shop">
  <orders>
    <order id="6001" currency="GBP">
      <placed_at>2026-10-01</placed_at>
      <customer><id>C1</id><name>Ada</name><address><city>London</city><country>GB</country></address></customer>
      <items><item><sku>A1</sku><qty>2</qty><price>9.5</price></item><item><sku>B2</sku><qty>1</qty><price>20</price></item></items>
    </order>
    <order id="6002" currency="EUR">
      <placed_at>2026-10-02</placed_at>
      <customer><id>C2</id><name>Bo</name><address><city>Paris</city><country>FR</country></address></customer>
      <items><item><sku>C3</sku><qty>5</qty><price>1</price></item><item><sku>D4</sku><qty>1</qty><price>3</price></item></items>
    </order>
    <order id="6003" currency="EUR">
      <placed_at>2026-10-03</placed_at>
      <customer><id>C3</id><name>Cy</name><address><city>Rome</city><country>IT</country></address></customer>
      <items><item><sku>E5</sku><qty>two</qty><price>4</price></item><item><sku>F6</sku><qty>1</qty><price>2</price></item></items>
    </order>
  </orders>
</export>
""")

import openpyxl
wb = openpyxl.Workbook()
ws = wb.active; ws.title = "Summary"
ws.append(["This tab is a cover sheet - not data"])
ws = wb.create_sheet("Orders")
ws.append(["Q4 order export - generated by finance"])          # row 1: title
ws.append(["order_id", "customer", "country", "amount"])        # row 2: header
ws.append([7001, "Ada", "GB", 10.5])
ws.append([7002, "Bo", "FR", 20])
ws.append([])                                                   # blank row: dropped
ws.append([7003, None, "IT", 5])                                # missing customer -> quarantined
ws.append([7004, "Di", "ES", -3])                               # negative -> quarantined
ws.append(["TOTAL", None, None, 32.5])                          # footer: skip_footer=1
wb.save(D / "orders_multitab.xlsx")
print("wrote", sorted(p.name for p in D.iterdir()))

# Fixed-width: a mainframe-style customer file, 44-character records. Layout as [start, end), 0-based:
#   customer_id [0,6] | name [6,26] | country [26,28] | signup_date [28,36] (YYYYMMDD) | amount_pence [36,44]
(D / "customers_fixed_width.txt").write_text(
    "HDR CUSTOMERS 20261007\n"                                   # header line: skip_rows=1
    "000123Ada Lovelace        GB2026100100001050\n"
    "000124Bob Smith           FR2026100200002000\n"
    "\n"                                                         # blank line: dropped
    "000125Cy Rossi            IT20261399000005X0\n"             # bad date (month 13) + bad amount
    "000126                    ES2026100400000300\n"             # missing name
    "000127Di Short            ES20261004\n"                       # cut off: 36 of 44 characters
    "TRL0000004\n"                                               # trailer: skip_footer=1
)

# ── Compressed: .gz (one file) and .zip (several, plus a file to ignore) ─────────
import gzip, zipfile
csv_text = "order_id,customer,amount\n8001,Ada,10.5\n8002,Bo,n/a\n8003,Cy,7\n"     # 8002: bad amount
with gzip.open(D / "orders.csv.gz", "wt", encoding="utf-8") as fh:
    fh.write(csv_text)
with zipfile.ZipFile(D / "orders_bundle.zip", "w", zipfile.ZIP_DEFLATED) as zf:
    zf.writestr("north/orders_north.csv", "order_id,customer,amount\n9001,Ada,5\n9002,,6\n")   # 9002: no customer
    zf.writestr("south/orders_south.csv", "order_id,customer,amount\n9101,Bo,8\n")
    zf.writestr("README.txt", "Export notes - not data")                                  # skipped by archive_member

# ── A European CSV: title line, semicolons, Latin-1, decimal commas, a multi-line note ──
(D / "orders_eu.csv").write_bytes((
    "Export Commandes - Octobre 2026\n"                       # title line: skip_rows=1
    "order_id;customer;amount;note\n"
    "10001;François;10,50;\"livraison rapide\"\n"
    "10002;Zoë;7,25;\"appeler avant\nla livraison\"\n"           # a line break inside quotes
    "10003;Jürgen;-2,00;\n"                                      # negative amount
).encode("latin-1"))

# ── Avro (Kafka / Debezium style): typed, with a nested record and an array ─────
import polars as pl
pl.DataFrame({
    "order_id": [11001, 11002, 11003],
    "customer": [{"name": "Ada", "tier": "gold"}, {"name": "Bo", "tier": "silver"}, {"name": None, "tier": "gold"}],
    "items": [[{"sku": "A1", "qty": 2}], [{"sku": "B2", "qty": 1}, {"sku": "C3", "qty": 3}], [{"sku": "D4", "qty": 1}]],
}).write_avro(D / "orders_events.avro")                                                  # 11003: no customer name

# ── Old Excel .xls: written once with xlwt and kept in data/, so running this needs no xlwt ──
if not (D / "orders_legacy.xls").exists():
    import datetime as dt
    import xlwt
    wb = xlwt.Workbook()
    ws = wb.add_sheet("Ledger")
    date_style = xlwt.easyxf(num_format_str="YYYY-MM-DD")
    ws.write(0, 0, "Legacy ledger export")                                               # row 1: title
    for c, h in enumerate(["order_id", "booked_on", "amount"]):
        ws.write(1, c, h)                                                                # row 2: header
    for r, (oid, day, amt) in enumerate([(12001, dt.date(2026, 10, 1), 15.0), (12002, dt.date(2026, 10, 2), -4.0)], start=2):
        ws.write(r, 0, oid); ws.write(r, 1, day, date_style); ws.write(r, 2, amt)        # 12002: negative
    wb.save(str(D / "orders_legacy.xls"))
