"""Scaffold a runnable medallion project from data contracts.

``scaffold_project`` takes loose contract YAMLs and emits a complete, ready-to-run
LakeLogic project::

    out/
      _registry.yaml            # DomainRegistry: contracts listed per layer
      contracts/bronze/*.yaml   # the contracts, laid out by target layer
      contracts/silver/*.yaml   #   (source bytes copied verbatim — the contract
      contracts/gold/*.yaml     #    stays canonical; nothing is re-serialized)
      run_pipeline.py           # entrypoint: DomainRegistry.from_yaml -> LakehousePipeline
      README.md                 # how to run + optional provenance

The contract is the source of truth: every input is validated through
:class:`~lakelogic.core.models.DataContract` before anything is written, contract files
are copied byte-for-byte (never re-serialized), and the generated registry/entrypoint
merely *arrange* them for the pipeline runner. Output is **deterministic** — the same
inputs always produce the same bytes — so a scaffold can be hash-stamped and diffed.

``provenance`` (optional) threads governance metadata into the generated files: a
control plane exporting an approved design passes e.g. the blueprint revision hash and
the review seal, and every generated file carries the trail. Standalone users omit it.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple, Union

import yaml
from loguru import logger

from lakelogic.core.models import DataContract
from lakelogic.core.yaml_utils import load_yaml

_LAYERS: Tuple[str, ...] = ("bronze", "silver", "gold")


class ScaffoldError(Exception):
    """A contract could not be scaffolded (invalid, unreadable, or ambiguous)."""


@dataclass(frozen=True)
class Provenance:
    """Optional governance trail stamped into generated files (never into contracts)."""

    generator: Optional[str] = None       # e.g. "LakeLogic Medallion Builder"
    revision_hash: Optional[str] = None   # the approved blueprint revision hash
    seal_hash: Optional[str] = None       # the governance review seal
    source: Optional[str] = None          # e.g. the estate/snapshot reference

    def lines(self) -> List[str]:
        pairs = [
            ("generated by", self.generator),
            ("revision", self.revision_hash),
            ("governance seal", self.seal_hash),
            ("source", self.source),
        ]
        return [f"{label}: {value}" for label, value in pairs if value]


@dataclass(frozen=True)
class ScaffoldResult:
    """What was written, for callers that bundle/deliver the project."""

    out_dir: Path
    registry_path: Path
    files: Tuple[Path, ...] = field(default=())


def _iter_contract_paths(contracts: Union[Path, Sequence[Path]]) -> List[Path]:
    if isinstance(contracts, (str, Path)):
        root = Path(contracts)
        if root.is_dir():
            paths = sorted(p for p in root.rglob("*.y*ml") if p.is_file())
        elif root.is_file():
            paths = [root]
        else:
            raise ScaffoldError(f"contracts path not found: {root}")
    else:
        paths = [Path(p) for p in contracts]
    if not paths:
        raise ScaffoldError("no contract YAML files found to scaffold")
    return paths


def _load_and_validate(path: Path) -> Tuple[dict, DataContract]:
    try:
        with open(path, "r", encoding="utf-8") as fh:
            raw = load_yaml(fh)
    except Exception as exc:  # unreadable / malformed YAML
        raise ScaffoldError(f"{path.name}: cannot parse YAML ({exc})") from exc
    if not isinstance(raw, dict):
        raise ScaffoldError(f"{path.name}: contract must be a YAML mapping")
    try:
        contract = DataContract(**raw)
    except Exception as exc:
        raise ScaffoldError(f"{path.name}: not a valid DataContract ({exc})") from exc
    return raw, contract


def _layer_of(raw: dict, contract: DataContract, path: Path) -> str:
    info = raw.get("info") or {}
    layer = str(info.get("target_layer") or "").strip().lower()
    if layer not in _LAYERS:
        raise ScaffoldError(
            f"{path.name}: info.target_layer must be one of {list(_LAYERS)} "
            f"(got {layer!r}) — the scaffold lays contracts out by medallion layer"
        )
    return layer


def _entity_of(raw: dict, contract: DataContract, path: Path) -> str:
    entity = (contract.dataset or "").strip() or path.stem
    return entity


def _header(comment: str, provenance: Optional[Provenance]) -> str:
    lines = [f"# {comment}"]
    if provenance:
        lines += [f"# {line}" for line in provenance.lines()]
    lines.append("# Generated by `lakelogic scaffold` — regenerate rather than hand-edit.")
    return "\n".join(lines)


def scaffold_project(
    contracts: Union[Path, Sequence[Path]],
    out_dir: Union[str, Path],
    *,
    domain: Optional[str] = None,
    system: Optional[str] = None,
    engine: str = "duckdb",
    environment: str = "dev",
    provenance: Optional[Provenance] = None,
) -> ScaffoldResult:
    """Render a runnable medallion project from contract YAMLs.

    Parameters
    ----------
    contracts:
        A directory of contract YAMLs (searched recursively), a single file, or an
        explicit list of paths.
    out_dir:
        Where to write the project (created if missing; existing files overwritten).
    domain / system:
        Registry identity. Defaults are taken from the first contract's
        ``info.domain`` / ``info.system``, falling back to ``"default"``.
    engine:
        The engine the generated entrypoint runs on (``duckdb`` default — the
        credential-free local target; ``polars`` / ``spark`` likewise valid).
    provenance:
        Optional governance trail stamped into the generated registry, entrypoint,
        and README (never into the contract files themselves).
    """
    out = Path(out_dir)
    paths = _iter_contract_paths(contracts)

    # Load + validate everything BEFORE writing anything (all-or-nothing).
    loaded: List[Tuple[str, str, Path, bytes]] = []  # (layer, entity, src, bytes)
    inferred_domain: Optional[str] = None
    inferred_system: Optional[str] = None
    seen: Dict[str, str] = {}
    for path in paths:
        raw, contract = _load_and_validate(path)
        layer = _layer_of(raw, contract, path)
        entity = _entity_of(raw, contract, path)
        if entity in seen:
            raise ScaffoldError(
                f"duplicate entity {entity!r} (layers {seen[entity]!r} and {layer!r}) — "
                "entities must be unique across the project"
            )
        seen[entity] = layer
        info = raw.get("info") or {}
        inferred_domain = inferred_domain or info.get("domain")
        inferred_system = inferred_system or info.get("system")
        loaded.append((layer, entity, path, path.read_bytes()))

    reg_domain = (domain or inferred_domain or "default").strip()
    reg_system = (system or inferred_system or "lakehouse").strip()

    # Deterministic order: medallion layer, then entity name.
    loaded.sort(key=lambda item: (_LAYERS.index(item[0]), item[1]))

    files: List[Path] = []

    # -- contracts, byte-for-byte -------------------------------------------
    for layer, entity, _src, data in loaded:
        target = out / "contracts" / layer / f"{entity}.yaml"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        files.append(target)

    # -- _registry.yaml ------------------------------------------------------
    registry: Dict[str, object] = {
        "domain": reg_domain,
        "system": reg_system,
        "storage_mode": "direct",
        # A local lake root: direct mode requires storage.external_location_root at run
        # time (the runner derives per-layer paths from it). "./lake" keeps the scaffold
        # runnable on a laptop; point it at abfss://... / s3://... for a cloud lake.
        "storage": {"external_location_root": "./lake"},
        "contracts": [
            {
                "layer": layer,
                "entity": entity,
                "path": f"contracts/{layer}/{entity}.yaml",
            }
            for layer, entity, _src, _data in loaded
        ],
    }
    if provenance and provenance.lines():
        registry["metadata"] = {
            "provenance": {
                key: value
                for key, value in (
                    ("generator", provenance.generator),
                    ("revision_hash", provenance.revision_hash),
                    ("seal_hash", provenance.seal_hash),
                    ("source", provenance.source),
                )
                if value
            }
        }
    registry_path = out / "_registry.yaml"
    registry_text = "\n".join(
        [
            _header(f"LakeLogic domain registry — {reg_domain}/{reg_system}", provenance),
            yaml.safe_dump(registry, sort_keys=False, default_flow_style=False),
        ]
    )
    registry_path.write_text(registry_text, encoding="utf-8", newline="\n")
    files.append(registry_path)

    # -- run_pipeline.py -----------------------------------------------------
    entry = out / "run_pipeline.py"
    entry.write_text(
        "\n".join(
            [
                _header("Run the medallion pipeline for this project.", provenance),
                "",
                "from pathlib import Path",
                "",
                "from lakelogic.core.registry import DomainRegistry",
                "from lakelogic.pipeline.runner import LakehousePipeline",
                "",
                "",
                "def main() -> None:",
                "    registry = DomainRegistry.from_yaml(",
                "        str(Path(__file__).parent / \"_registry.yaml\"),",
                f"        environment={environment!r},",
                "        storage_mode=\"direct\",",
                "    )",
                f"    LakehousePipeline(registry, engine={engine!r}).run()",
                "",
                "",
                "if __name__ == \"__main__\":",
                "    main()",
                "",
            ]
        ),
        encoding="utf-8",
        newline="\n",
    )
    files.append(entry)

    # -- README.md -----------------------------------------------------------
    counts = {layer: sum(1 for l, *_ in loaded if l == layer) for layer in _LAYERS}
    prov_block = ""
    if provenance and provenance.lines():
        prov_block = "\n".join(["", "## Provenance", ""] + [f"- {line}" for line in provenance.lines()]) + "\n"
    readme = out / "README.md"
    readme.write_text(
        f"""# {reg_domain}/{reg_system} — medallion lakehouse project

Generated by `lakelogic scaffold`. The **contracts are the source of truth** — the
registry and entrypoint only arrange them for the pipeline runner; regenerate this
project rather than hand-editing generated files.

Layers: {counts['bronze']} bronze / {counts['silver']} silver / {counts['gold']} gold.

## Run

```bash
pip install lakelogic
python run_pipeline.py          # engine: {engine}
```

The registry's `storage.external_location_root` defaults to `./lake` (a local folder);
point it at your `abfss://` / `s3://` / `gs://` lake for cloud storage. Bronze contracts
read from their own `source:` config — make sure it points at your landed data.

## Validate contracts

```bash
lakelogic validate contracts/ --recursive
```
{prov_block}""",
        encoding="utf-8",
        newline="\n",
    )
    files.append(readme)

    logger.info(
        "scaffolded {} contract(s) into {} ({} bronze / {} silver / {} gold)",
        len(loaded), out, counts["bronze"], counts["silver"], counts["gold"],
    )
    return ScaffoldResult(out_dir=out, registry_path=registry_path, files=tuple(files))
