"""Scaffold a runnable medallion project from data contracts.

``scaffold_project`` takes loose contract YAMLs and emits a complete, ready-to-run
LakeLogic project::

    out/
      _registry.yaml            # DomainRegistry: contracts listed per layer
      contracts/bronze/*.yaml   # the contracts, laid out by target layer
      contracts/silver/*.yaml   #   (source bytes copied verbatim — the contract
      contracts/gold/*.yaml     #    stays canonical; nothing is re-serialized)
      run_pipeline.py           # entrypoint: DomainRegistry.from_yaml -> LakehousePipeline
      README.md                 # how to run + optional provenance

The contract is the source of truth: every input is validated through
:class:`~lakelogic.core.models.DataContract` before anything is written, contract files
are copied byte-for-byte (never re-serialized), and the generated registry/entrypoint
merely *arrange* them for the pipeline runner. Output is **deterministic** — the same
inputs always produce the same bytes — so a scaffold can be hash-stamped and diffed.

``provenance`` (optional) threads governance metadata into the generated files: a
control plane exporting an approved design passes e.g. the blueprint revision hash and
the review seal, and every generated file carries the trail. Standalone users omit it.

``target`` picks the *platform flavor* of the runnable surface. Contracts and the
registry are identical across targets — only the thin execution wrapper changes:

- ``python`` (default): ``run_pipeline.py`` running the whole pipeline (duckdb default).
- ``fabric``: per-layer ``notebooks/NN_<layer>.ipynb`` Jupyter notebooks that read the
  project from the attached lakehouse's OneLake ``Files/`` mount and run that layer on
  the ambient Fabric Spark session.
- ``databricks``: per-layer ``notebooks/NN_<layer>.py`` notebooks in Databricks source
  format plus a ``databricks.yml`` asset bundle whose job chains bronze -> silver -> gold.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple, Union

import yaml
from loguru import logger

from lakelogic.core.models import DataContract
from lakelogic.core.yaml_utils import load_yaml

_LAYERS: Tuple[str, ...] = ("bronze", "silver", "gold")
_LAYER_ORDINAL: Dict[str, str] = {"bronze": "01", "silver": "02", "gold": "03"}
_TARGETS: Tuple[str, ...] = ("python", "fabric", "databricks")

# Where the generated registry points its direct-mode storage root, per target. Each is
# the most-runnable default for that platform (README explains how to repoint it).
_STORAGE_ROOTS: Dict[str, str] = {
    "python": "./lake",
    "fabric": "/lakehouse/default/Files/lake",  # OneLake, via the default-lakehouse mount
    "databricks": "/Volumes/main/default/lake",  # a Unity Catalog volume
}


class ScaffoldError(Exception):
    """A contract could not be scaffolded (invalid, unreadable, or ambiguous)."""


@dataclass(frozen=True)
class Provenance:
    """Optional governance trail stamped into generated files (never into contracts)."""

    generator: Optional[str] = None       # e.g. "LakeLogic Medallion Builder"
    revision_hash: Optional[str] = None   # the approved blueprint revision hash
    seal_hash: Optional[str] = None       # the governance review seal
    source: Optional[str] = None          # e.g. the estate/snapshot reference

    def lines(self) -> List[str]:
        pairs = [
            ("generated by", self.generator),
            ("revision", self.revision_hash),
            ("governance seal", self.seal_hash),
            ("source", self.source),
        ]
        return [f"{label}: {value}" for label, value in pairs if value]


@dataclass(frozen=True)
class ScaffoldResult:
    """What was written, for callers that bundle/deliver the project."""

    out_dir: Path
    registry_path: Path
    files: Tuple[Path, ...] = field(default=())


def _iter_contract_paths(contracts: Union[Path, Sequence[Path]]) -> List[Path]:
    if isinstance(contracts, (str, Path)):
        root = Path(contracts)
        if root.is_dir():
            paths = sorted(p for p in root.rglob("*.y*ml") if p.is_file())
        elif root.is_file():
            paths = [root]
        else:
            raise ScaffoldError(f"contracts path not found: {root}")
    else:
        paths = [Path(p) for p in contracts]
    if not paths:
        raise ScaffoldError("no contract YAML files found to scaffold")
    return paths


def _load_and_validate(path: Path) -> Tuple[dict, DataContract]:
    try:
        with open(path, "r", encoding="utf-8") as fh:
            raw = load_yaml(fh)
    except Exception as exc:  # unreadable / malformed YAML
        raise ScaffoldError(f"{path.name}: cannot parse YAML ({exc})") from exc
    if not isinstance(raw, dict):
        raise ScaffoldError(f"{path.name}: contract must be a YAML mapping")
    try:
        contract = DataContract(**raw)
    except Exception as exc:
        raise ScaffoldError(f"{path.name}: not a valid DataContract ({exc})") from exc
    return raw, contract


def _layer_of(raw: dict, contract: DataContract, path: Path) -> str:
    info = raw.get("info") or {}
    layer = str(info.get("target_layer") or "").strip().lower()
    if layer not in _LAYERS:
        raise ScaffoldError(
            f"{path.name}: info.target_layer must be one of {list(_LAYERS)} "
            f"(got {layer!r}) — the scaffold lays contracts out by medallion layer"
        )
    return layer


def _entity_of(raw: dict, contract: DataContract, path: Path) -> str:
    entity = (contract.dataset or "").strip() or path.stem
    return entity


def _header(comment: str, provenance: Optional[Provenance]) -> str:
    lines = [f"# {comment}"]
    if provenance:
        lines += [f"# {line}" for line in provenance.lines()]
    lines.append("# Generated by `lakelogic scaffold` — regenerate rather than hand-edit.")
    return "\n".join(lines)


# ── Notebook flavors (fabric / databricks) ──────────────────────────────────
#
# The notebooks are deliberately THIN: load the generated `_registry.yaml`, hand the
# platform's ambient Spark session to `LakehousePipeline`, run one layer. All logic
# stays in the contracts + runner — the notebook is only the platform's front door.


def _notebook_markdown(
    layer: str, reg_domain: str, reg_system: str, provenance: Optional[Provenance]
) -> str:
    lines = [
        f"# {reg_domain}/{reg_system} — {layer}",
        "",
        f"Runs the **{layer}** layer of the medallion pipeline from this project's",
        "data contracts (the contracts are the source of truth — edit them, not this",
        "notebook, and regenerate with `lakelogic scaffold`).",
    ]
    if provenance and provenance.lines():
        lines += [""] + [f"- {line}" for line in provenance.lines()]
    return "\n".join(lines)


def _run_layer_lines(layer: str, environment: str) -> List[str]:
    """The registry-load + single-layer run body (imports/PROJECT_ROOT prepended per flavor)."""
    return [
        "registry = DomainRegistry.from_yaml(",
        '    f"{PROJECT_ROOT}/_registry.yaml",',
        f"    environment={environment!r},",
        '    storage_mode="direct",',
        ")",
        f'LakehousePipeline(registry, engine="spark", spark=spark).run(target_layers={layer!r})',
    ]


_RUNNER_IMPORTS: List[str] = [
    "from lakelogic.core.registry import DomainRegistry",
    "from lakelogic.pipeline.runner import LakehousePipeline",
]


def _fabric_notebook(
    layer: str,
    reg_domain: str,
    reg_system: str,
    environment: str,
    provenance: Optional[Provenance],
) -> str:
    """A standard nbformat-4.5 Jupyter notebook, importable into a Fabric workspace."""
    project_files = f"/lakehouse/default/Files/{reg_domain}_{reg_system}"
    run_lines = _RUNNER_IMPORTS + [
        "",
        "# This project's folder, uploaded into the attached lakehouse's OneLake Files/",
        "# area (adjust if you uploaded it elsewhere). Requires a default lakehouse.",
        f"PROJECT_ROOT = {project_files!r}",
        "",
    ] + _run_layer_lines(layer, environment)

    def _cell_source(lines: List[str]) -> List[str]:
        return [line + "\n" for line in lines[:-1]] + [lines[-1]]

    notebook = {
        "cells": [
            {
                "cell_type": "markdown",
                "id": "header",
                "metadata": {},
                "source": _cell_source(
                    _notebook_markdown(layer, reg_domain, reg_system, provenance).split("\n")
                ),
            },
            {
                "cell_type": "code",
                "id": "install",
                "metadata": {},
                "execution_count": None,
                "outputs": [],
                "source": ["%pip install lakelogic"],
            },
            {
                "cell_type": "code",
                "id": "run",
                "metadata": {},
                "execution_count": None,
                "outputs": [],
                "source": _cell_source(run_lines),
            },
        ],
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    return json.dumps(notebook, indent=1, ensure_ascii=False) + "\n"


def _databricks_notebook(
    layer: str,
    reg_domain: str,
    reg_system: str,
    environment: str,
    provenance: Optional[Provenance],
) -> str:
    """Databricks source-format notebook (a plain .py file the workspace renders as cells)."""
    md = _notebook_markdown(layer, reg_domain, reg_system, provenance).split("\n")
    run_lines = ["from pathlib import Path", ""] + _RUNNER_IMPORTS + [
        "",
        "# The bundle/project root — this notebook lives in notebooks/, the registry and",
        "# contracts one level up. Adjust if you moved the notebook.",
        "PROJECT_ROOT = str(Path.cwd().parent)",
        "",
    ] + _run_layer_lines(layer, environment)
    lines = ["# Databricks notebook source"]
    lines += ["# MAGIC %md"] + [f"# MAGIC {line}".rstrip() for line in md]
    lines += ["", "# COMMAND ----------", "", "# MAGIC %pip install lakelogic"]
    lines += ["", "# COMMAND ----------", ""] + run_lines
    return "\n".join(lines) + "\n"


def _databricks_bundle(
    layers_present: List[str],
    reg_domain: str,
    reg_system: str,
    provenance: Optional[Provenance],
) -> str:
    """A Databricks asset bundle: one job chaining the per-layer notebooks in order."""
    tasks: List[Dict[str, object]] = []
    previous: Optional[str] = None
    for layer in layers_present:
        task: Dict[str, object] = {
            "task_key": layer,
            "notebook_task": {
                "notebook_path": f"./notebooks/{_LAYER_ORDINAL[layer]}_{layer}.py"
            },
        }
        if previous:
            task["depends_on"] = [{"task_key": previous}]
        tasks.append(task)
        previous = layer
    bundle = {
        "bundle": {"name": f"{reg_domain}_{reg_system}"},
        "targets": {"dev": {"mode": "development", "default": True}},
        "resources": {
            "jobs": {
                "medallion_run": {
                    "name": f"{reg_domain}/{reg_system} — medallion run",
                    "tasks": tasks,
                }
            }
        },
    }
    return "\n".join(
        [
            _header(f"Databricks asset bundle — {reg_domain}/{reg_system}", provenance),
            yaml.safe_dump(bundle, sort_keys=False, default_flow_style=False, allow_unicode=True),
        ]
    )


def scaffold_project(
    contracts: Union[Path, Sequence[Path]],
    out_dir: Union[str, Path],
    *,
    domain: Optional[str] = None,
    system: Optional[str] = None,
    target: str = "python",
    engine: Optional[str] = None,
    environment: str = "dev",
    provenance: Optional[Provenance] = None,
) -> ScaffoldResult:
    """Render a runnable medallion project from contract YAMLs.

    Parameters
    ----------
    contracts:
        A directory of contract YAMLs (searched recursively), a single file, or an
        explicit list of paths.
    out_dir:
        Where to write the project (created if missing; existing files overwritten).
    domain / system:
        Registry identity. Defaults are taken from the first contract's
        ``info.domain`` / ``info.system``, falling back to ``"default"``.
    target:
        Platform flavor of the runnable surface: ``python`` (a ``run_pipeline.py``
        entrypoint), ``fabric`` (per-layer ``.ipynb`` notebooks over OneLake), or
        ``databricks`` (per-layer source-format notebooks + a ``databricks.yml``
        asset bundle). Contracts and registry are identical across targets.
    engine:
        The engine the generated entrypoint runs on. Defaults to ``duckdb`` for the
        ``python`` target (the credential-free local engine; ``polars`` / ``spark``
        likewise valid); the notebook targets run on Spark and reject anything else.
    provenance:
        Optional governance trail stamped into the generated registry, entrypoint,
        and README (never into the contract files themselves).
    """
    if target not in _TARGETS:
        raise ScaffoldError(f"target must be one of {list(_TARGETS)} (got {target!r})")
    resolved_engine = engine or ("duckdb" if target == "python" else "spark")
    if target != "python" and resolved_engine != "spark":
        raise ScaffoldError(
            f"target {target!r} runs on the platform's Spark session — "
            f"engine must be 'spark' (got {resolved_engine!r})"
        )
    out = Path(out_dir)
    paths = _iter_contract_paths(contracts)

    # Load + validate everything BEFORE writing anything (all-or-nothing).
    loaded: List[Tuple[str, str, Path, bytes]] = []  # (layer, entity, src, bytes)
    inferred_domain: Optional[str] = None
    inferred_system: Optional[str] = None
    seen: Dict[str, str] = {}
    for path in paths:
        raw, contract = _load_and_validate(path)
        layer = _layer_of(raw, contract, path)
        entity = _entity_of(raw, contract, path)
        if entity in seen:
            raise ScaffoldError(
                f"duplicate entity {entity!r} (layers {seen[entity]!r} and {layer!r}) — "
                "entities must be unique across the project"
            )
        seen[entity] = layer
        info = raw.get("info") or {}
        inferred_domain = inferred_domain or info.get("domain")
        inferred_system = inferred_system or info.get("system")
        loaded.append((layer, entity, path, path.read_bytes()))

    reg_domain = (domain or inferred_domain or "default").strip()
    reg_system = (system or inferred_system or "lakehouse").strip()

    # Deterministic order: medallion layer, then entity name.
    loaded.sort(key=lambda item: (_LAYERS.index(item[0]), item[1]))

    files: List[Path] = []

    # -- contracts, byte-for-byte -------------------------------------------
    for layer, entity, _src, data in loaded:
        dest = out / "contracts" / layer / f"{entity}.yaml"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(data)
        files.append(dest)

    # -- _registry.yaml ------------------------------------------------------
    registry: Dict[str, object] = {
        "domain": reg_domain,
        "system": reg_system,
        "storage_mode": "direct",
        # Direct mode requires storage.external_location_root at run time (the runner
        # derives per-layer paths from it). Each target gets its most-runnable default:
        # a local folder for python, the OneLake Files mount for fabric, a UC volume
        # for databricks — the README explains how to repoint it.
        "storage": {"external_location_root": _STORAGE_ROOTS[target]},
        "contracts": [
            {
                "layer": layer,
                "entity": entity,
                "path": f"contracts/{layer}/{entity}.yaml",
            }
            for layer, entity, _src, _data in loaded
        ],
    }
    if provenance and provenance.lines():
        registry["metadata"] = {
            "provenance": {
                key: value
                for key, value in (
                    ("generator", provenance.generator),
                    ("revision_hash", provenance.revision_hash),
                    ("seal_hash", provenance.seal_hash),
                    ("source", provenance.source),
                )
                if value
            }
        }
    registry_path = out / "_registry.yaml"
    registry_text = "\n".join(
        [
            _header(f"LakeLogic domain registry — {reg_domain}/{reg_system}", provenance),
            yaml.safe_dump(registry, sort_keys=False, default_flow_style=False),
        ]
    )
    registry_path.write_text(registry_text, encoding="utf-8", newline="\n")
    files.append(registry_path)

    layers_present = [
        layer for layer in _LAYERS if any(item[0] == layer for item in loaded)
    ]

    # -- runnable surface, per target ---------------------------------------
    if target == "python":
        entry = out / "run_pipeline.py"
        entry.write_text(
            "\n".join(
                [
                    _header("Run the medallion pipeline for this project.", provenance),
                    "",
                    "from pathlib import Path",
                    "",
                    "from lakelogic.core.registry import DomainRegistry",
                    "from lakelogic.pipeline.runner import LakehousePipeline",
                    "",
                    "",
                    "def main() -> None:",
                    "    registry = DomainRegistry.from_yaml(",
                    "        str(Path(__file__).parent / \"_registry.yaml\"),",
                    f"        environment={environment!r},",
                    "        storage_mode=\"direct\",",
                    "    )",
                    f"    LakehousePipeline(registry, engine={resolved_engine!r}).run()",
                    "",
                    "",
                    "if __name__ == \"__main__\":",
                    "    main()",
                    "",
                ]
            ),
            encoding="utf-8",
            newline="\n",
        )
        files.append(entry)
    else:
        for layer in layers_present:
            if target == "fabric":
                name = f"{_LAYER_ORDINAL[layer]}_{layer}.ipynb"
                content = _fabric_notebook(layer, reg_domain, reg_system, environment, provenance)
            else:
                name = f"{_LAYER_ORDINAL[layer]}_{layer}.py"
                content = _databricks_notebook(
                    layer, reg_domain, reg_system, environment, provenance
                )
            notebook_path = out / "notebooks" / name
            notebook_path.parent.mkdir(parents=True, exist_ok=True)
            notebook_path.write_text(content, encoding="utf-8", newline="\n")
            files.append(notebook_path)
        if target == "databricks":
            bundle_path = out / "databricks.yml"
            bundle_path.write_text(
                _databricks_bundle(layers_present, reg_domain, reg_system, provenance),
                encoding="utf-8",
                newline="\n",
            )
            files.append(bundle_path)

    # -- README.md -----------------------------------------------------------
    counts = {layer: sum(1 for item in loaded if item[0] == layer) for layer in _LAYERS}
    prov_block = ""
    if provenance and provenance.lines():
        prov_block = "\n".join(["", "## Provenance", ""] + [f"- {line}" for line in provenance.lines()]) + "\n"
    if target == "python":
        run_block = f"""## Run

```bash
pip install lakelogic
python run_pipeline.py          # engine: {resolved_engine}
```

The registry's `storage.external_location_root` defaults to `./lake` (a local folder);
point it at your `abfss://` / `s3://` / `gs://` lake for cloud storage."""
    elif target == "fabric":
        run_block = f"""## Run (Microsoft Fabric)

1. Upload this project folder into your lakehouse's **Files/** area as
   `Files/{reg_domain}_{reg_system}` (OneLake file explorer, or the Fabric portal).
2. Import the notebooks from `notebooks/` into your workspace and attach that
   lakehouse as the **default lakehouse** for each.
3. Run them in order: {" → ".join(f"`{_LAYER_ORDINAL[layer]}_{layer}`" for layer in layers_present)}.

The registry's `storage.external_location_root` defaults to
`/lakehouse/default/Files/lake` — the attached lakehouse's OneLake mount — so the
medallion tables land in OneLake. Repoint it (e.g. at an `abfss://` path) to write
elsewhere."""
    else:
        run_block = """## Run (Databricks)

```bash
databricks bundle deploy
databricks bundle run medallion_run
```

The bundle's `medallion_run` job chains the per-layer notebooks in order. The
registry's `storage.external_location_root` defaults to `/Volumes/main/default/lake`
— create that Unity Catalog volume (`CREATE VOLUME main.default.lake`) or repoint it
at a volume you already have."""
    surface = "entrypoint" if target == "python" else "notebooks"
    readme = out / "README.md"
    readme.write_text(
        f"""# {reg_domain}/{reg_system} — medallion lakehouse project

Generated by `lakelogic scaffold`. The **contracts are the source of truth** — the
registry and {surface} only arrange them for the pipeline runner; regenerate this
project rather than hand-editing generated files.

Layers: {counts['bronze']} bronze / {counts['silver']} silver / {counts['gold']} gold.

{run_block}

Bronze contracts read from their own `source:` config — make sure it points at your
landed data.

## Validate contracts

```bash
lakelogic validate contracts/ --recursive
```
{prov_block}""",
        encoding="utf-8",
        newline="\n",
    )
    files.append(readme)

    logger.info(
        "scaffolded {} contract(s) into {} ({} bronze / {} silver / {} gold)",
        len(loaded), out, counts["bronze"], counts["silver"], counts["gold"],
    )
    return ScaffoldResult(out_dir=out, registry_path=registry_path, files=tuple(files))
